#ifndef GUARD_CONSTANTS_SPECIES_H
#define GUARD_CONSTANTS_SPECIES_H

// species defines
#define SPECIES_NONE			0
#define SPECIES_BULBASAUR		1
#define SPECIES_IVYSAUR			2
#define SPECIES_VENUSAUR		3
#define SPECIES_CHARMANDER		4
#define SPECIES_CHARMELEON		5
#define SPECIES_CHARIZARD		6
#define SPECIES_SQUIRTLE		7
#define SPECIES_WARTORTLE		8
#define SPECIES_BLASTOISE		9
#define SPECIES_CATERPIE		10
#define SPECIES_METAPOD			11
#define SPECIES_BUTTERFREE		12
#define SPECIES_WEEDLE			13
#define SPECIES_KAKUNA			14
#define SPECIES_BEEDRILL		15
#define SPECIES_PIDGEY			16
#define SPECIES_PIDGEOTTO		17
#define SPECIES_PIDGEOT			18
#define SPECIES_RATTATA			19
#define SPECIES_RATICATE		20
#define SPECIES_SPEAROW			21
#define SPECIES_FEAROW			22
#define SPECIES_EKANS			23
#define SPECIES_ARBOK			24
#define SPECIES_PICHU			25
#define SPECIES_PIKACHU			26
#define SPECIES_RAICHU			27
#define SPECIES_SANDSHREW		28
#define SPECIES_SANDSLASH		29
#define SPECIES_NIDORAN_F		30
#define SPECIES_NIDORINA		31
#define SPECIES_NIDOQUEEN		32
#define SPECIES_NIDORAN_M		33
#define SPECIES_NIDORINO		34
#define SPECIES_NIDOKING		35
#define SPECIES_CLEFFA			36
#define SPECIES_CLEFAIRY		37
#define SPECIES_CLEFABLE		38
#define SPECIES_VULPIX			39
#define SPECIES_NINETALES		40
#define SPECIES_IGGLYBUFF		41
#define SPECIES_JIGGLYPUFF		42
#define SPECIES_WIGGLYTUFF		43
#define SPECIES_ZUBAT			44
#define SPECIES_GOLBAT			45
#define SPECIES_CROBAT			46
#define SPECIES_ODDISH			47
#define SPECIES_GLOOM			48
#define SPECIES_VILEPLUME		49
#define SPECIES_BELLOSSOM		50
#define SPECIES_PARAS			51
#define SPECIES_PARASECT		52
#define SPECIES_VENONAT			53
#define SPECIES_VENOMOTH		54
#define SPECIES_DIGLETT			55
#define SPECIES_DUGTRIO			56
#define SPECIES_MEOWTH			57
#define SPECIES_PERSIAN			58
#define SPECIES_PSYDUCK			59
#define SPECIES_GOLDUCK			60
#define SPECIES_MANKEY			61
#define SPECIES_PRIMEAPE		62
#define SPECIES_GROWLITHE		63
#define SPECIES_ARCANINE		64
#define SPECIES_POLIWAG			65
#define SPECIES_POLIWHIRL		66
#define SPECIES_POLIWRATH		67
#define SPECIES_POLITOED		68
#define SPECIES_ABRA			69
#define SPECIES_KADABRA			70
#define SPECIES_ALAKAZAM		71
#define SPECIES_MACHOP			72
#define SPECIES_MACHOKE			73
#define SPECIES_MACHAMP			74
#define SPECIES_BELLSPROUT		75
#define SPECIES_WEEPINBELL		76
#define SPECIES_VICTREEBEL		77
#define SPECIES_TENTACOOL		78
#define SPECIES_TENTACRUEL		79
#define SPECIES_GEODUDE			80
#define SPECIES_GRAVELER		81
#define SPECIES_GOLEM			82
#define SPECIES_PONYTA			83
#define SPECIES_RAPIDASH		84
#define SPECIES_SLOWPOKE		85
#define SPECIES_SLOWBRO			86
#define SPECIES_SLOWKING		87
#define SPECIES_MAGNEMITE		88
#define SPECIES_MAGNETON		89
#define SPECIES_MAGNEZONE		90
#define SPECIES_FARFETCHD		91
#define SPECIES_SIRFETCHD		92
#define SPECIES_DODUO			93
#define SPECIES_DODRIO			94
#define SPECIES_SEEL			95
#define SPECIES_DEWGONG			96
#define SPECIES_GRIMER			97
#define SPECIES_MUK				98
#define SPECIES_SHELLDER		99
#define SPECIES_CLOYSTER		100
#define SPECIES_GASTLY			101
#define SPECIES_HAUNTER			102
#define SPECIES_GENGAR			103
#define SPECIES_ONIX			104
#define SPECIES_STEELIX			105
#define SPECIES_DROWZEE			106
#define SPECIES_HYPNO			107
#define SPECIES_KRABBY			108
#define SPECIES_KINGLER			109
#define SPECIES_VOLTORB			110
#define SPECIES_ELECTRODE		111
#define SPECIES_EXEGGCUTE		112
#define SPECIES_EXEGGUTOR		113
#define SPECIES_CUBONE			114
#define SPECIES_MAROWAK			115
#define SPECIES_TYROGUE			116
#define SPECIES_HITMONLEE		117
#define SPECIES_HITMONCHAN		118
#define SPECIES_HITMONTOP		119
#define SPECIES_LICKITUNG		120
#define SPECIES_LICKILICKY		121
#define SPECIES_KOFFING			122
#define SPECIES_WEEZING			123
#define SPECIES_RHYHORN			124
#define SPECIES_RHYDON			125
#define SPECIES_RHYPERIOR		126
#define SPECIES_HAPPINY			127
#define SPECIES_CHANSEY			128
#define SPECIES_BLISSEY			129
#define SPECIES_TANGELA			130
#define SPECIES_TANGROWTH		131
#define SPECIES_KANGASKHAN		132
#define SPECIES_HORSEA			133
#define SPECIES_SEADRA			134
#define SPECIES_KINGDRA			135
#define SPECIES_GOLDEEN			136
#define SPECIES_SEAKING			137
#define SPECIES_STARYU			138
#define SPECIES_STARMIE			139
#define SPECIES_MIME_JR			140
#define SPECIES_MR_MIME			141
#define SPECIES_SCYTHER			142
#define SPECIES_SCIZOR			143
#define SPECIES_SMOOCHUM		144
#define SPECIES_JYNX			145
#define SPECIES_ELEKID			146
#define SPECIES_ELECTABUZZ		147
#define SPECIES_ELECTIVIRE		148
#define SPECIES_MAGBY			149
#define SPECIES_MAGMAR			150
#define SPECIES_MAGMORTAR		151
#define SPECIES_PINSIR			152
#define SPECIES_TAUROS			153
#define SPECIES_MAGIKARP		154
#define SPECIES_GYARADOS		155
#define SPECIES_LAPRAS			156
#define SPECIES_DITTO			157
#define SPECIES_EEVEE			158
#define SPECIES_VAPOREON		159
#define SPECIES_JOLTEON			160
#define SPECIES_FLAREON			161
#define SPECIES_ESPEON			162
#define SPECIES_UMBREON			163
#define SPECIES_LEAFEON			164
#define SPECIES_GLACEON			165
#define SPECIES_SYLVEON			166
#define SPECIES_PORYGON			167
#define SPECIES_PORYGON2		168
#define SPECIES_PORYGON_Z		169
#define SPECIES_OMANYTE			170
#define SPECIES_OMASTAR			171
#define SPECIES_KABUTO			172
#define SPECIES_KABUTOPS		173
#define SPECIES_AERODACTYL		174
#define SPECIES_MUNCHLAX		175
#define SPECIES_SNORLAX			176
#define SPECIES_ARTICUNO		177
#define SPECIES_ZAPDOS			178
#define SPECIES_MOLTRES			179
#define SPECIES_DRATINI			180
#define SPECIES_DRAGONAIR		181
#define SPECIES_DRAGONITE		182
#define SPECIES_MEWTWO			183
#define SPECIES_MEW				184

#define KANTO_DEX_COUNT			SPECIES_MEW

#define SPECIES_CHIKORITA		185
#define SPECIES_BAYLEEF			186
#define SPECIES_MEGANIUM		187
#define SPECIES_CYNDAQUIL		188
#define SPECIES_QUILAVA			189
#define SPECIES_TYPHLOSION		190
#define SPECIES_TOTODILE		191
#define SPECIES_CROCONAW		192
#define SPECIES_FERALIGATR		193
#define SPECIES_SENTRET			194
#define SPECIES_FURRET			195
#define SPECIES_HOOTHOOT		196
#define SPECIES_NOCTOWL			197
#define SPECIES_LEDYBA			198
#define SPECIES_LEDIAN			199
#define SPECIES_SPINARAK		200
#define SPECIES_ARIADOS			201
#define SPECIES_CHINCHOU		202
#define SPECIES_LANTURN			203
#define SPECIES_TOGEPI			204
#define SPECIES_TOGETIC			205
#define SPECIES_TOGEKISS		206
#define SPECIES_NATU			207
#define SPECIES_XATU			208
#define SPECIES_MAREEP			209
#define SPECIES_FLAAFFY			210
#define SPECIES_AMPHAROS		211
#define SPECIES_AZURILL			212
#define SPECIES_MARILL			213
#define SPECIES_AZUMARILL		214
#define SPECIES_BONSLY			215
#define SPECIES_SUDOWOODO		216
#define SPECIES_HOPPIP			217
#define SPECIES_SKIPLOOM		218
#define SPECIES_JUMPLUFF		219
#define SPECIES_AIPOM			220
#define SPECIES_AMBIPOM			221
#define SPECIES_SUNKERN			222
#define SPECIES_SUNFLORA		223
#define SPECIES_YANMA			224
#define SPECIES_YANMEGA			225
#define SPECIES_WOOPER			226
#define SPECIES_QUAGSIRE		227
#define SPECIES_MURKROW			228
#define SPECIES_HONCHKROW		229
#define SPECIES_MISDREAVUS		230
#define SPECIES_MISMAGIUS		231
#define SPECIES_UNOWN			232
#define SPECIES_WYNAUT			233
#define SPECIES_WOBBUFFET		234
#define SPECIES_GIRAFARIG		235
#define SPECIES_PINECO			236
#define SPECIES_FORRETRESS		237
#define SPECIES_DUNSPARCE		238
#define SPECIES_GLIGAR			239
#define SPECIES_GLISCOR			240
#define SPECIES_SNUBBULL		241
#define SPECIES_GRANBULL		242
#define SPECIES_QWILFISH		243
#define SPECIES_SHUCKLE			244
#define SPECIES_HERACROSS		245
#define SPECIES_SNEASEL			246
#define SPECIES_WEAVILE			247
#define SPECIES_TEDDIURSA		248
#define SPECIES_URSARING		249
#define SPECIES_SLUGMA			250
#define SPECIES_MAGCARGO		251
#define SPECIES_SWINUB			252
#define SPECIES_PILOSWINE		253
#define SPECIES_MAMOSWINE		254
#define SPECIES_CORSOLA			255
#define SPECIES_REMORAID		256
#define SPECIES_OCTILLERY		257
#define SPECIES_DELIBIRD		258
#define SPECIES_MANTYKE			259
#define SPECIES_MANTINE			260
#define SPECIES_SKARMORY		261
#define SPECIES_HOUNDOUR		262
#define SPECIES_HOUNDOOM		263
#define SPECIES_PHANPY			264
#define SPECIES_DONPHAN			265
#define SPECIES_STANTLER		266
#define SPECIES_SMEARGLE		267
#define SPECIES_MILTANK			268
#define SPECIES_RAIKOU			269
#define SPECIES_ENTEI			270
#define SPECIES_SUICUNE			271
#define SPECIES_LARVITAR		272
#define SPECIES_PUPITAR			273
#define SPECIES_TYRANITAR		274
#define SPECIES_LUGIA			275
#define SPECIES_HO_OH			276
#define SPECIES_CELEBI			277

#define JOHTO_DEX_COUNT SPECIES_CELEBI

#define SPECIES_TREECKO			278
#define SPECIES_GROVYLE			279
#define SPECIES_SCEPTILE		280
#define SPECIES_TORCHIC			281
#define SPECIES_COMBUSKEN		282
#define SPECIES_BLAZIKEN		283
#define SPECIES_MUDKIP			284
#define SPECIES_MARSHTOMP		285
#define SPECIES_SWAMPERT		286
#define SPECIES_POOCHYENA		287
#define SPECIES_MIGHTYENA		288
#define SPECIES_ZIGZAGOON		289
#define SPECIES_LINOONE			290
#define SPECIES_WURMPLE			291
#define SPECIES_SILCOON			292
#define SPECIES_BEAUTIFLY		293
#define SPECIES_CASCOON			294
#define SPECIES_DUSTOX			295
#define SPECIES_LOTAD			296
#define SPECIES_LOMBRE			297
#define SPECIES_LUDICOLO		298
#define SPECIES_SEEDOT			299
#define SPECIES_NUZLEAF			300
#define SPECIES_SHIFTRY			301
#define SPECIES_TAILLOW			302
#define SPECIES_SWELLOW			303
#define SPECIES_WINGULL			304
#define SPECIES_PELIPPER		305
#define SPECIES_RALTS			306
#define SPECIES_KIRLIA			307
#define SPECIES_GARDEVOIR		308
#define SPECIES_GALLADE			309
#define SPECIES_SURSKIT			310
#define SPECIES_MASQUERAIN		311
#define SPECIES_SHROOMISH		312
#define SPECIES_BRELOOM			313
#define SPECIES_SLAKOTH			314
#define SPECIES_VIGOROTH		315
#define SPECIES_SLAKING			316
#define SPECIES_NINCADA			317
#define SPECIES_NINJASK			318
#define SPECIES_SHEDINJA		319
#define SPECIES_WHISMUR			320
#define SPECIES_LOUDRED			321
#define SPECIES_EXPLOUD			322
#define SPECIES_MAKUHITA		323
#define SPECIES_HARIYAMA		324
#define SPECIES_NOSEPASS		325
#define SPECIES_PROBOPASS		326
#define SPECIES_SKITTY			327
#define SPECIES_DELCATTY		328
#define SPECIES_SABLEYE			329
#define SPECIES_MAWILE			330
#define SPECIES_ARON			331
#define SPECIES_LAIRON			332
#define SPECIES_AGGRON			333
#define SPECIES_MEDITITE		334
#define SPECIES_MEDICHAM		335
#define SPECIES_ELECTRIKE		336
#define SPECIES_MANECTRIC		337
#define SPECIES_PLUSLE			338
#define SPECIES_MINUN			339
#define SPECIES_VOLBEAT			340
#define SPECIES_ILLUMISE		341
#define SPECIES_BUDEW			342
#define SPECIES_ROSELIA			343
#define SPECIES_ROSERADE		344
#define SPECIES_GULPIN			345
#define SPECIES_SWALOT			346
#define SPECIES_CARVANHA		347
#define SPECIES_SHARPEDO		348
#define SPECIES_WAILMER			349
#define SPECIES_WAILORD			350
#define SPECIES_NUMEL			351
#define SPECIES_CAMERUPT		352
#define SPECIES_TORKOAL			353
#define SPECIES_SPOINK			354
#define SPECIES_GRUMPIG			355
#define SPECIES_SPINDA			356
#define SPECIES_TRAPINCH		357
#define SPECIES_VIBRAVA			358
#define SPECIES_FLYGON			359
#define SPECIES_CACNEA			360
#define SPECIES_CACTURNE		361
#define SPECIES_SWABLU			362
#define SPECIES_ALTARIA			363
#define SPECIES_ZANGOOSE		364
#define SPECIES_SEVIPER			365
#define SPECIES_LUNATONE		366
#define SPECIES_SOLROCK			367
#define SPECIES_BARBOACH		368
#define SPECIES_WHISCASH		369
#define SPECIES_CORPHISH		370
#define SPECIES_CRAWDAUNT		371
#define SPECIES_BALTOY			372
#define SPECIES_CLAYDOL			373
#define SPECIES_LILEEP			374
#define SPECIES_CRADILY			375
#define SPECIES_ANORITH			376
#define SPECIES_ARMALDO			377
#define SPECIES_FEEBAS			378
#define SPECIES_MILOTIC			379
#define SPECIES_CASTFORM		380
#define SPECIES_KECLEON			381
#define SPECIES_SHUPPET			382
#define SPECIES_BANETTE			383
#define SPECIES_DUSKULL			384
#define SPECIES_DUSCLOPS		385
#define SPECIES_DUSKNOIR		386
#define SPECIES_TROPIUS			387
#define SPECIES_CHINGLING		388
#define SPECIES_CHIMECHO		389
#define SPECIES_ABSOL			390
#define SPECIES_SNORUNT			391
#define SPECIES_GLALIE			392
#define SPECIES_FROSLASS		393
#define SPECIES_SPHEAL			394
#define SPECIES_SEALEO			395
#define SPECIES_WALREIN			396
#define SPECIES_CLAMPERL		397
#define SPECIES_HUNTAIL			398
#define SPECIES_GOREBYSS		399
#define SPECIES_RELICANTH		400
#define SPECIES_LUVDISC			401
#define SPECIES_ALOMOMOLA		402
#define SPECIES_BAGON			403
#define SPECIES_SHELGON			404
#define SPECIES_SALAMENCE		405
#define SPECIES_BELDUM			406
#define SPECIES_METANG			407
#define SPECIES_METAGROSS		408
#define SPECIES_REGIROCK		409
#define SPECIES_REGICE			410
#define SPECIES_REGISTEEL		411
#define SPECIES_LATIAS			412
#define SPECIES_LATIOS			413
#define SPECIES_KYOGRE			414
#define SPECIES_GROUDON			415
#define SPECIES_RAYQUAZA		416
#define SPECIES_JIRACHI			417
#define SPECIES_DEOXYS			418

#define HOENN_DEX_COUNT		SPECIES_DEOXYS

#define SPECIES_TURTWIG			419
#define SPECIES_GROTLE			420
#define SPECIES_TORTERRA		421
#define SPECIES_CHIMCHAR		422
#define SPECIES_MONFERNO		423
#define SPECIES_INFERNAPE		424
#define SPECIES_PIPLUP			425
#define SPECIES_PRINPLUP		426
#define SPECIES_EMPOLEON		427
#define SPECIES_STARLY			428
#define SPECIES_STARAVIA		429
#define SPECIES_STARAPTOR		430
#define SPECIES_BIDOOF			431
#define SPECIES_BIBAREL			432
#define SPECIES_KRICKETOT		433
#define SPECIES_KRICKETUNE		434
#define SPECIES_SHINX			435
#define SPECIES_LUXIO			436
#define SPECIES_LUXRAY			437
#define SPECIES_CRANIDOS		438
#define SPECIES_RAMPARDOS		439
#define SPECIES_SHIELDON		440
#define SPECIES_BASTIODON		441
#define SPECIES_BURMY			442
#define SPECIES_WORMADAM		443
#define SPECIES_MOTHIM			444
#define SPECIES_COMBEE			445
#define SPECIES_VESPIQUEN		446
#define SPECIES_PACHIRISU		447
#define SPECIES_BUIZEL			448
#define SPECIES_FLOATZEL		449
#define SPECIES_CHERUBI			450
#define SPECIES_CHERRIM			451
#define SPECIES_SHELLOS			452
#define SPECIES_GASTRODON		453
#define SPECIES_DRIFLOON		454
#define SPECIES_DRIFBLIM		455
#define SPECIES_BUNEARY			456
#define SPECIES_LOPUNNY			457
#define SPECIES_GLAMEOW			458
#define SPECIES_PURUGLY			459
#define SPECIES_STUNKY			460
#define SPECIES_SKUNTANK		461
#define SPECIES_BRONZOR			462
#define SPECIES_BRONZONG		463
#define SPECIES_CHATOT			464
#define SPECIES_SPIRITOMB		465
#define SPECIES_GIBLE			466
#define SPECIES_GABITE			467
#define SPECIES_GARCHOMP		468
#define SPECIES_RIOLU			469
#define SPECIES_LUCARIO			470
#define SPECIES_HIPPOPOTAS		471
#define SPECIES_HIPPOWDON		472
#define SPECIES_SKORUPI			473
#define SPECIES_DRAPION			474
#define SPECIES_CROAGUNK		475
#define SPECIES_TOXICROAK		476
#define SPECIES_CARNIVINE		477
#define SPECIES_FINNEON			478
#define SPECIES_LUMINEON		479
#define SPECIES_SNOVER			480
#define SPECIES_ABOMASNOW		481
#define SPECIES_ROTOM			482
#define SPECIES_UXIE			483
#define SPECIES_MESPRIT			484
#define SPECIES_AZELF			485
#define SPECIES_DIALGA			486
#define SPECIES_PALKIA			487
#define SPECIES_HEATRAN			488
#define SPECIES_REGIGIGAS		489
#define SPECIES_GIRATINA		490
#define SPECIES_CRESSELIA		491
#define SPECIES_PHIONE			492
#define SPECIES_MANAPHY			493
#define SPECIES_DARKRAI			494
#define SPECIES_SHAYMIN			495
#define SPECIES_ARCEUS			496

#define SINNOH_DEX_COUNT		SPECIES_ARCEUS

#define FORMS_START SPECIES_ARCEUS
	// Megas
#define SPECIES_VENUSAUR_MEGA                FORMS_START + 1
#define SPECIES_CHARIZARD_MEGA_X             FORMS_START + 2
#define SPECIES_CHARIZARD_MEGA_Y             FORMS_START + 3
#define SPECIES_BLASTOISE_MEGA               FORMS_START + 4
#define SPECIES_BEEDRILL_MEGA                FORMS_START + 5
#define SPECIES_PIDGEOT_MEGA                 FORMS_START + 6
#define SPECIES_ALAKAZAM_MEGA                FORMS_START + 7
#define SPECIES_SLOWBRO_MEGA                 FORMS_START + 8
#define SPECIES_GENGAR_MEGA                  FORMS_START + 9
#define SPECIES_KANGASKHAN_MEGA              FORMS_START + 10
#define SPECIES_PINSIR_MEGA                  FORMS_START + 11
#define SPECIES_GYARADOS_MEGA                FORMS_START + 12
#define SPECIES_AERODACTYL_MEGA              FORMS_START + 13
#define SPECIES_MEWTWO_MEGA_X                FORMS_START + 14
#define SPECIES_MEWTWO_MEGA_Y                FORMS_START + 15
#define SPECIES_AMPHAROS_MEGA                FORMS_START + 16
#define SPECIES_STEELIX_MEGA                 FORMS_START + 17
#define SPECIES_SCIZOR_MEGA                  FORMS_START + 18
#define SPECIES_HERACROSS_MEGA               FORMS_START + 19
#define SPECIES_HOUNDOOM_MEGA                FORMS_START + 20
#define SPECIES_TYRANITAR_MEGA               FORMS_START + 21
#define SPECIES_SCEPTILE_MEGA                FORMS_START + 22
#define SPECIES_BLAZIKEN_MEGA                FORMS_START + 23
#define SPECIES_SWAMPERT_MEGA                FORMS_START + 24
#define SPECIES_GARDEVOIR_MEGA               FORMS_START + 25
#define SPECIES_SABLEYE_MEGA                 FORMS_START + 26
#define SPECIES_MAWILE_MEGA                  FORMS_START + 27
#define SPECIES_AGGRON_MEGA                  FORMS_START + 28
#define SPECIES_MEDICHAM_MEGA                FORMS_START + 29
#define SPECIES_MANECTRIC_MEGA               FORMS_START + 30
#define SPECIES_SHARPEDO_MEGA                FORMS_START + 31
#define SPECIES_CAMERUPT_MEGA                FORMS_START + 32
#define SPECIES_ALTARIA_MEGA                 FORMS_START + 33
#define SPECIES_BANETTE_MEGA                 FORMS_START + 34
#define SPECIES_ABSOL_MEGA                   FORMS_START + 35
#define SPECIES_GLALIE_MEGA                  FORMS_START + 36
#define SPECIES_SALAMENCE_MEGA               FORMS_START + 37
#define SPECIES_METAGROSS_MEGA               FORMS_START + 38
#define SPECIES_LATIAS_MEGA                  FORMS_START + 39
#define SPECIES_LATIOS_MEGA                  FORMS_START + 40
#define SPECIES_LOPUNNY_MEGA                 FORMS_START + 41
#define SPECIES_GARCHOMP_MEGA                FORMS_START + 42
#define SPECIES_LUCARIO_MEGA                 FORMS_START + 43
#define SPECIES_ABOMASNOW_MEGA               FORMS_START + 44
#define SPECIES_GALLADE_MEGA                 FORMS_START + 45

// Special Mega + Primals
#define SPECIES_RAYQUAZA_MEGA                FORMS_START + 48
#define SPECIES_KYOGRE_PRIMAL                FORMS_START + 49
#define SPECIES_GROUDON_PRIMAL               FORMS_START + 50

// Alolan Forms
#define SPECIES_RATTATA_ALOLAN               FORMS_START + 51
#define SPECIES_RATICATE_ALOLAN              FORMS_START + 52
#define SPECIES_RAICHU_ALOLAN                FORMS_START + 53
#define SPECIES_SANDSHREW_ALOLAN             FORMS_START + 54
#define SPECIES_SANDSLASH_ALOLAN             FORMS_START + 55
#define SPECIES_VULPIX_ALOLAN                FORMS_START + 56
#define SPECIES_NINETALES_ALOLAN             FORMS_START + 57
#define SPECIES_DIGLETT_ALOLAN               FORMS_START + 58
#define SPECIES_DUGTRIO_ALOLAN               FORMS_START + 59
#define SPECIES_MEOWTH_ALOLAN                FORMS_START + 60
#define SPECIES_PERSIAN_ALOLAN               FORMS_START + 61
#define SPECIES_GEODUDE_ALOLAN               FORMS_START + 62
#define SPECIES_GRAVELER_ALOLAN              FORMS_START + 63
#define SPECIES_GOLEM_ALOLAN                 FORMS_START + 64
#define SPECIES_GRIMER_ALOLAN                FORMS_START + 65
#define SPECIES_MUK_ALOLAN                   FORMS_START + 66
#define SPECIES_EXEGGUTOR_ALOLAN             FORMS_START + 67
#define SPECIES_MAROWAK_ALOLAN               FORMS_START + 68

// Galarian Forms
#define SPECIES_MEOWTH_GALARIAN              FORMS_START + 69
#define SPECIES_PONYTA_GALARIAN              FORMS_START + 70
#define SPECIES_RAPIDASH_GALARIAN            FORMS_START + 71
#define SPECIES_SLOWPOKE_GALARIAN            FORMS_START + 72
#define SPECIES_SLOWBRO_GALARIAN             FORMS_START + 73
#define SPECIES_FARFETCHD_GALARIAN           FORMS_START + 74
#define SPECIES_WEEZING_GALARIAN             FORMS_START + 75
#define SPECIES_ARTICUNO_GALARIAN            FORMS_START + 76
#define SPECIES_ZAPDOS_GALARIAN              FORMS_START + 77
#define SPECIES_MOLTRES_GALARIAN             FORMS_START + 78
#define SPECIES_SLOWKING_GALARIAN            FORMS_START + 79
#define SPECIES_CORSOLA_GALARIAN             FORMS_START + 80
#define SPECIES_ZIGZAGOON_GALARIAN           FORMS_START + 81
#define SPECIES_LINOONE_GALARIAN             FORMS_START + 82

// Misc Forms

// Cosplay Pikachu
#define SPECIES_PIKACHU_COSPLAY              FORMS_START + 83
#define SPECIES_PIKACHU_ROCK_STAR            FORMS_START + 84
#define SPECIES_PIKACHU_BELLE                FORMS_START + 85
#define SPECIES_PIKACHU_POP_STAR             FORMS_START + 86
#define SPECIES_PIKACHU_PH_D                 FORMS_START + 87
#define SPECIES_PIKACHU_LIBRE                FORMS_START + 88

// Cap Pikachu
#define SPECIES_PIKACHU_ORIGINAL_CAP         FORMS_START + 89
#define SPECIES_PIKACHU_HOENN_CAP            FORMS_START + 90
#define SPECIES_PIKACHU_SINNOH_CAP           FORMS_START + 91
#define SPECIES_PIKACHU_UNOVA_CAP            FORMS_START + 92
#define SPECIES_PIKACHU_KALOS_CAP            FORMS_START + 93
#define SPECIES_PIKACHU_ALOLA_CAP            FORMS_START + 94
#define SPECIES_PIKACHU_PARTNER_CAP          FORMS_START + 95
#define SPECIES_PIKACHU_WORLD_CAP            FORMS_START + 96

// Pichu
#define SPECIES_PICHU_SPIKY_EARED            FORMS_START + 97

// Unown
#define SPECIES_UNOWN_B                      FORMS_START + 98
#define SPECIES_UNOWN_C                      FORMS_START + 99
#define SPECIES_UNOWN_D                      FORMS_START + 100
#define SPECIES_UNOWN_E                      FORMS_START + 101
#define SPECIES_UNOWN_F                      FORMS_START + 102
#define SPECIES_UNOWN_G                      FORMS_START + 103
#define SPECIES_UNOWN_H                      FORMS_START + 104
#define SPECIES_UNOWN_I                      FORMS_START + 105
#define SPECIES_UNOWN_J                      FORMS_START + 106
#define SPECIES_UNOWN_K                      FORMS_START + 107
#define SPECIES_UNOWN_L                      FORMS_START + 108
#define SPECIES_UNOWN_M                      FORMS_START + 109
#define SPECIES_UNOWN_N                      FORMS_START + 110
#define SPECIES_UNOWN_O                      FORMS_START + 111
#define SPECIES_UNOWN_P                      FORMS_START + 112
#define SPECIES_UNOWN_Q                      FORMS_START + 113
#define SPECIES_UNOWN_R                      FORMS_START + 114
#define SPECIES_UNOWN_S                      FORMS_START + 115
#define SPECIES_UNOWN_T                      FORMS_START + 116
#define SPECIES_UNOWN_U                      FORMS_START + 117
#define SPECIES_UNOWN_V                      FORMS_START + 118
#define SPECIES_UNOWN_W                      FORMS_START + 119
#define SPECIES_UNOWN_X                      FORMS_START + 120
#define SPECIES_UNOWN_Y                      FORMS_START + 121
#define SPECIES_UNOWN_Z                      FORMS_START + 122
#define SPECIES_UNOWN_EMARK                  FORMS_START + 123
#define SPECIES_UNOWN_QMARK                  FORMS_START + 124

// Castform
#define SPECIES_CASTFORM_SUNNY               FORMS_START + 125
#define SPECIES_CASTFORM_RAINY               FORMS_START + 126
#define SPECIES_CASTFORM_SNOWY               FORMS_START + 127
#define SPECIES_CASTFORM_SANDY				 FORMS_START + 128

// Deoxys
#define SPECIES_DEOXYS_ATTACK                FORMS_START + 129
#define SPECIES_DEOXYS_DEFENSE               FORMS_START + 130
#define SPECIES_DEOXYS_SPEED                 FORMS_START + 131

// Burmy
#define SPECIES_BURMY_SANDY_CLOAK            FORMS_START + 132
#define SPECIES_BURMY_TRASH_CLOAK            FORMS_START + 133

// Wormadam
#define SPECIES_WORMADAM_SANDY_CLOAK         FORMS_START + 134
#define SPECIES_WORMADAM_TRASH_CLOAK         FORMS_START + 135

// Cherrim
#define SPECIES_CHERRIM_SUNSHINE             FORMS_START + 136

// Shellos
#define SPECIES_SHELLOS_EAST_SEA             FORMS_START + 137

// Gastrodon
#define SPECIES_GASTRODON_EAST_SEA           FORMS_START + 138

// Rotom
#define SPECIES_ROTOM_HEAT                   FORMS_START + 139
#define SPECIES_ROTOM_WASH                   FORMS_START + 140
#define SPECIES_ROTOM_FROST                  FORMS_START + 141
#define SPECIES_ROTOM_FAN                    FORMS_START + 142
#define SPECIES_ROTOM_MOW                    FORMS_START + 143

// Giratina
#define SPECIES_GIRATINA_ORIGIN              FORMS_START + 144

// Shaymin
#define SPECIES_SHAYMIN_SKY                  FORMS_START + 145

// Arceus
#define SPECIES_ARCEUS_FIGHTING              FORMS_START + 146
#define SPECIES_ARCEUS_FLYING                FORMS_START + 147
#define SPECIES_ARCEUS_POISON                FORMS_START + 148
#define SPECIES_ARCEUS_GROUND                FORMS_START + 149
#define SPECIES_ARCEUS_ROCK                  FORMS_START + 150
#define SPECIES_ARCEUS_BUG                   FORMS_START + 151
#define SPECIES_ARCEUS_GHOST                 FORMS_START + 152
#define SPECIES_ARCEUS_STEEL                 FORMS_START + 153
#define SPECIES_ARCEUS_FIRE                  FORMS_START + 154
#define SPECIES_ARCEUS_WATER                 FORMS_START + 155
#define SPECIES_ARCEUS_GRASS                 FORMS_START + 156
#define SPECIES_ARCEUS_ELECTRIC              FORMS_START + 157
#define SPECIES_ARCEUS_PSYCHIC               FORMS_START + 158
#define SPECIES_ARCEUS_ICE                   FORMS_START + 159
#define SPECIES_ARCEUS_DRAGON                FORMS_START + 160
#define SPECIES_ARCEUS_DARK                  FORMS_START + 161
#define SPECIES_ARCEUS_FAIRY                 FORMS_START + 162

#define SPECIES_GOLEM_MAGMA					 FORMS_START + 163

#define SPECIES_FORMS_FILLER				 FORMS_START + 199

#define SPECIES_EGG SPECIES_FORMS_FILLER + 1
#define NUM_SPECIES SPECIES_EGG

// National Dex Index Defines
#define NATIONAL_DEX_NONE			0
#define NATIONAL_DEX_BULBASAUR		1
#define NATIONAL_DEX_IVYSAUR			2
#define NATIONAL_DEX_VENUSAUR		3
#define NATIONAL_DEX_CHARMANDER		4
#define NATIONAL_DEX_CHARMELEON		5
#define NATIONAL_DEX_CHARIZARD		6
#define NATIONAL_DEX_SQUIRTLE		7
#define NATIONAL_DEX_WARTORTLE		8
#define NATIONAL_DEX_BLASTOISE		9
#define NATIONAL_DEX_CATERPIE		10
#define NATIONAL_DEX_METAPOD			11
#define NATIONAL_DEX_BUTTERFREE		12
#define NATIONAL_DEX_WEEDLE			13
#define NATIONAL_DEX_KAKUNA			14
#define NATIONAL_DEX_BEEDRILL		15
#define NATIONAL_DEX_PIDGEY			16
#define NATIONAL_DEX_PIDGEOTTO		17
#define NATIONAL_DEX_PIDGEOT			18
#define NATIONAL_DEX_RATTATA			19
#define NATIONAL_DEX_RATICATE		20
#define NATIONAL_DEX_SPEAROW			21
#define NATIONAL_DEX_FEAROW			22
#define NATIONAL_DEX_EKANS			23
#define NATIONAL_DEX_ARBOK			24
#define NATIONAL_DEX_PICHU			25
#define NATIONAL_DEX_PIKACHU			26
#define NATIONAL_DEX_RAICHU			27
#define NATIONAL_DEX_SANDSHREW		28
#define NATIONAL_DEX_SANDSLASH		29
#define NATIONAL_DEX_NIDORAN_F		30
#define NATIONAL_DEX_NIDORINA		31
#define NATIONAL_DEX_NIDOQUEEN		32
#define NATIONAL_DEX_NIDORAN_M		33
#define NATIONAL_DEX_NIDORINO		34
#define NATIONAL_DEX_NIDOKING		35
#define NATIONAL_DEX_CLEFFA			36
#define NATIONAL_DEX_CLEFAIRY		37
#define NATIONAL_DEX_CLEFABLE		38
#define NATIONAL_DEX_VULPIX			39
#define NATIONAL_DEX_NINETALES		40
#define NATIONAL_DEX_IGGLYBUFF		41
#define NATIONAL_DEX_JIGGLYPUFF		42
#define NATIONAL_DEX_WIGGLYTUFF		43
#define NATIONAL_DEX_ZUBAT			44
#define NATIONAL_DEX_GOLBAT			45
#define NATIONAL_DEX_CROBAT			46
#define NATIONAL_DEX_ODDISH			47
#define NATIONAL_DEX_GLOOM			48
#define NATIONAL_DEX_VILEPLUME		49
#define NATIONAL_DEX_BELLOSSOM		50
#define NATIONAL_DEX_PARAS			51
#define NATIONAL_DEX_PARASECT		52
#define NATIONAL_DEX_VENONAT			53
#define NATIONAL_DEX_VENOMOTH		54
#define NATIONAL_DEX_DIGLETT			55
#define NATIONAL_DEX_DUGTRIO			56
#define NATIONAL_DEX_MEOWTH			57
#define NATIONAL_DEX_PERSIAN			58
#define NATIONAL_DEX_PSYDUCK			59
#define NATIONAL_DEX_GOLDUCK			60
#define NATIONAL_DEX_MANKEY			61
#define NATIONAL_DEX_PRIMEAPE		62
#define NATIONAL_DEX_GROWLITHE		63
#define NATIONAL_DEX_ARCANINE		64
#define NATIONAL_DEX_POLIWAG			65
#define NATIONAL_DEX_POLIWHIRL		66
#define NATIONAL_DEX_POLIWRATH		67
#define NATIONAL_DEX_POLITOED		68
#define NATIONAL_DEX_ABRA			69
#define NATIONAL_DEX_KADABRA			70
#define NATIONAL_DEX_ALAKAZAM		71
#define NATIONAL_DEX_MACHOP			72
#define NATIONAL_DEX_MACHOKE			73
#define NATIONAL_DEX_MACHAMP			74
#define NATIONAL_DEX_BELLSPROUT		75
#define NATIONAL_DEX_WEEPINBELL		76
#define NATIONAL_DEX_VICTREEBEL		77
#define NATIONAL_DEX_TENTACOOL		78
#define NATIONAL_DEX_TENTACRUEL		79
#define NATIONAL_DEX_GEODUDE			80
#define NATIONAL_DEX_GRAVELER		81
#define NATIONAL_DEX_GOLEM			82
#define NATIONAL_DEX_PONYTA			83
#define NATIONAL_DEX_RAPIDASH		84
#define NATIONAL_DEX_SLOWPOKE		85
#define NATIONAL_DEX_SLOWBRO			86
#define NATIONAL_DEX_SLOWKING		87
#define NATIONAL_DEX_MAGNEMITE		88
#define NATIONAL_DEX_MAGNETON		89
#define NATIONAL_DEX_MAGNEZONE		90
#define NATIONAL_DEX_FARFETCHD		91
#define NATIONAL_DEX_SIRFETCHD		92
#define NATIONAL_DEX_DODUO			93
#define NATIONAL_DEX_DODRIO			94
#define NATIONAL_DEX_SEEL			95
#define NATIONAL_DEX_DEWGONG			96
#define NATIONAL_DEX_GRIMER			97
#define NATIONAL_DEX_MUK				98
#define NATIONAL_DEX_SHELLDER		99
#define NATIONAL_DEX_CLOYSTER		100
#define NATIONAL_DEX_GASTLY			101
#define NATIONAL_DEX_HAUNTER			102
#define NATIONAL_DEX_GENGAR			103
#define NATIONAL_DEX_ONIX			104
#define NATIONAL_DEX_STEELIX			105
#define NATIONAL_DEX_DROWZEE			106
#define NATIONAL_DEX_HYPNO			107
#define NATIONAL_DEX_KRABBY			108
#define NATIONAL_DEX_KINGLER			109
#define NATIONAL_DEX_VOLTORB			110
#define NATIONAL_DEX_ELECTRODE		111
#define NATIONAL_DEX_EXEGGCUTE		112
#define NATIONAL_DEX_EXEGGUTOR		113
#define NATIONAL_DEX_CUBONE			114
#define NATIONAL_DEX_MAROWAK			115
#define NATIONAL_DEX_TYROGUE			116
#define NATIONAL_DEX_HITMONLEE		117
#define NATIONAL_DEX_HITMONCHAN		118
#define NATIONAL_DEX_HITMONTOP		119
#define NATIONAL_DEX_LICKITUNG		120
#define NATIONAL_DEX_LICKILICKY		121
#define NATIONAL_DEX_KOFFING			122
#define NATIONAL_DEX_WEEZING			123
#define NATIONAL_DEX_RHYHORN			124
#define NATIONAL_DEX_RHYDON			125
#define NATIONAL_DEX_RHYPERIOR		126
#define NATIONAL_DEX_HAPPINY			127
#define NATIONAL_DEX_CHANSEY			128
#define NATIONAL_DEX_BLISSEY			129
#define NATIONAL_DEX_TANGELA			130
#define NATIONAL_DEX_TANGROWTH		131
#define NATIONAL_DEX_KANGASKHAN		132
#define NATIONAL_DEX_HORSEA			133
#define NATIONAL_DEX_SEADRA			134
#define NATIONAL_DEX_KINGDRA			135
#define NATIONAL_DEX_GOLDEEN			136
#define NATIONAL_DEX_SEAKING			137
#define NATIONAL_DEX_STARYU			138
#define NATIONAL_DEX_STARMIE			139
#define NATIONAL_DEX_MIME_JR			140
#define NATIONAL_DEX_MR_MIME			141
#define NATIONAL_DEX_SCYTHER			142
#define NATIONAL_DEX_SCIZOR			143
#define NATIONAL_DEX_SMOOCHUM		144
#define NATIONAL_DEX_JYNX			145
#define NATIONAL_DEX_ELEKID			146
#define NATIONAL_DEX_ELECTABUZZ		147
#define NATIONAL_DEX_ELECTIVIRE		148
#define NATIONAL_DEX_MAGBY			149
#define NATIONAL_DEX_MAGMAR			150
#define NATIONAL_DEX_MAGMORTAR		151
#define NATIONAL_DEX_PINSIR			152
#define NATIONAL_DEX_TAUROS			153
#define NATIONAL_DEX_MAGIKARP		154
#define NATIONAL_DEX_GYARADOS		155
#define NATIONAL_DEX_LAPRAS			156
#define NATIONAL_DEX_DITTO			157
#define NATIONAL_DEX_EEVEE			158
#define NATIONAL_DEX_VAPOREON		159
#define NATIONAL_DEX_JOLTEON			160
#define NATIONAL_DEX_FLAREON			161
#define NATIONAL_DEX_ESPEON			162
#define NATIONAL_DEX_UMBREON			163
#define NATIONAL_DEX_LEAFEON			164
#define NATIONAL_DEX_GLACEON			165
#define NATIONAL_DEX_SYLVEON			166
#define NATIONAL_DEX_PORYGON			167
#define NATIONAL_DEX_PORYGON2		168
#define NATIONAL_DEX_PORYGON_Z		169
#define NATIONAL_DEX_OMANYTE			170
#define NATIONAL_DEX_OMASTAR			171
#define NATIONAL_DEX_KABUTO			172
#define NATIONAL_DEX_KABUTOPS		173
#define NATIONAL_DEX_AERODACTYL		174
#define NATIONAL_DEX_MUNCHLAX		175
#define NATIONAL_DEX_SNORLAX			176
#define NATIONAL_DEX_ARTICUNO		177
#define NATIONAL_DEX_ZAPDOS			178
#define NATIONAL_DEX_MOLTRES			179
#define NATIONAL_DEX_DRATINI			180
#define NATIONAL_DEX_DRAGONAIR		181
#define NATIONAL_DEX_DRAGONITE		182
#define NATIONAL_DEX_MEWTWO			183
#define NATIONAL_DEX_MEW				184
#define NATIONAL_DEX_CHIKORITA		185
#define NATIONAL_DEX_BAYLEEF			186
#define NATIONAL_DEX_MEGANIUM		187
#define NATIONAL_DEX_CYNDAQUIL		188
#define NATIONAL_DEX_QUILAVA			189
#define NATIONAL_DEX_TYPHLOSION		190
#define NATIONAL_DEX_TOTODILE		191
#define NATIONAL_DEX_CROCONAW		192
#define NATIONAL_DEX_FERALIGATR		193
#define NATIONAL_DEX_SENTRET			194
#define NATIONAL_DEX_FURRET			195
#define NATIONAL_DEX_HOOTHOOT		196
#define NATIONAL_DEX_NOCTOWL			197
#define NATIONAL_DEX_LEDYBA			198
#define NATIONAL_DEX_LEDIAN			199
#define NATIONAL_DEX_SPINARAK		200
#define NATIONAL_DEX_ARIADOS			201
#define NATIONAL_DEX_CHINCHOU		202
#define NATIONAL_DEX_LANTURN			203
#define NATIONAL_DEX_TOGEPI			204
#define NATIONAL_DEX_TOGETIC			205
#define NATIONAL_DEX_TOGEKISS		206
#define NATIONAL_DEX_NATU			207
#define NATIONAL_DEX_XATU			208
#define NATIONAL_DEX_MAREEP			209
#define NATIONAL_DEX_FLAAFFY			210
#define NATIONAL_DEX_AMPHAROS		211
#define NATIONAL_DEX_AZURILL			212
#define NATIONAL_DEX_MARILL			213
#define NATIONAL_DEX_AZUMARILL		214
#define NATIONAL_DEX_BONSLY			215
#define NATIONAL_DEX_SUDOWOODO		216
#define NATIONAL_DEX_HOPPIP			217
#define NATIONAL_DEX_SKIPLOOM		218
#define NATIONAL_DEX_JUMPLUFF		219
#define NATIONAL_DEX_AIPOM			220
#define NATIONAL_DEX_AMBIPOM			221
#define NATIONAL_DEX_SUNKERN			222
#define NATIONAL_DEX_SUNFLORA		223
#define NATIONAL_DEX_YANMA			224
#define NATIONAL_DEX_YANMEGA			225
#define NATIONAL_DEX_WOOPER			226
#define NATIONAL_DEX_QUAGSIRE		227
#define NATIONAL_DEX_MURKROW			228
#define NATIONAL_DEX_HONCHKROW		229
#define NATIONAL_DEX_MISDREAVUS		230
#define NATIONAL_DEX_MISMAGIUS		231
#define NATIONAL_DEX_UNOWN			232
#define NATIONAL_DEX_WYNAUT			233
#define NATIONAL_DEX_WOBBUFFET		234
#define NATIONAL_DEX_GIRAFARIG		235
#define NATIONAL_DEX_PINECO			236
#define NATIONAL_DEX_FORRETRESS		237
#define NATIONAL_DEX_DUNSPARCE		238
#define NATIONAL_DEX_GLIGAR			239
#define NATIONAL_DEX_GLISCOR			240
#define NATIONAL_DEX_SNUBBULL		241
#define NATIONAL_DEX_GRANBULL		242
#define NATIONAL_DEX_QWILFISH		243
#define NATIONAL_DEX_SHUCKLE			244
#define NATIONAL_DEX_HERACROSS		245
#define NATIONAL_DEX_SNEASEL			246
#define NATIONAL_DEX_WEAVILE			247
#define NATIONAL_DEX_TEDDIURSA		248
#define NATIONAL_DEX_URSARING		249
#define NATIONAL_DEX_SLUGMA			250
#define NATIONAL_DEX_MAGCARGO		251
#define NATIONAL_DEX_SWINUB			252
#define NATIONAL_DEX_PILOSWINE		253
#define NATIONAL_DEX_MAMOSWINE		254
#define NATIONAL_DEX_CORSOLA			255
#define NATIONAL_DEX_REMORAID		256
#define NATIONAL_DEX_OCTILLERY		257
#define NATIONAL_DEX_DELIBIRD		258
#define NATIONAL_DEX_MANTYKE			259
#define NATIONAL_DEX_MANTINE			260
#define NATIONAL_DEX_SKARMORY		261
#define NATIONAL_DEX_HOUNDOUR		262
#define NATIONAL_DEX_HOUNDOOM		263
#define NATIONAL_DEX_PHANPY			264
#define NATIONAL_DEX_DONPHAN			265
#define NATIONAL_DEX_STANTLER		266
#define NATIONAL_DEX_SMEARGLE		267
#define NATIONAL_DEX_MILTANK			268
#define NATIONAL_DEX_RAIKOU			269
#define NATIONAL_DEX_ENTEI			270
#define NATIONAL_DEX_SUICUNE			271
#define NATIONAL_DEX_LARVITAR		272
#define NATIONAL_DEX_PUPITAR			273
#define NATIONAL_DEX_TYRANITAR		274
#define NATIONAL_DEX_LUGIA			275
#define NATIONAL_DEX_HO_OH			276
#define NATIONAL_DEX_CELEBI			277
#define NATIONAL_DEX_TREECKO			278
#define NATIONAL_DEX_GROVYLE			279
#define NATIONAL_DEX_SCEPTILE		280
#define NATIONAL_DEX_TORCHIC			281
#define NATIONAL_DEX_COMBUSKEN		282
#define NATIONAL_DEX_BLAZIKEN		283
#define NATIONAL_DEX_MUDKIP			284
#define NATIONAL_DEX_MARSHTOMP		285
#define NATIONAL_DEX_SWAMPERT		286
#define NATIONAL_DEX_POOCHYENA		287
#define NATIONAL_DEX_MIGHTYENA		288
#define NATIONAL_DEX_ZIGZAGOON		289
#define NATIONAL_DEX_LINOONE			290
#define NATIONAL_DEX_WURMPLE			291
#define NATIONAL_DEX_SILCOON			292
#define NATIONAL_DEX_BEAUTIFLY		293
#define NATIONAL_DEX_CASCOON			294
#define NATIONAL_DEX_DUSTOX			295
#define NATIONAL_DEX_LOTAD			296
#define NATIONAL_DEX_LOMBRE			297
#define NATIONAL_DEX_LUDICOLO		298
#define NATIONAL_DEX_SEEDOT			299
#define NATIONAL_DEX_NUZLEAF			300
#define NATIONAL_DEX_SHIFTRY			301
#define NATIONAL_DEX_TAILLOW			302
#define NATIONAL_DEX_SWELLOW			303
#define NATIONAL_DEX_WINGULL			304
#define NATIONAL_DEX_PELIPPER		305
#define NATIONAL_DEX_RALTS			306
#define NATIONAL_DEX_KIRLIA			307
#define NATIONAL_DEX_GARDEVOIR		308
#define NATIONAL_DEX_GALLADE			309
#define NATIONAL_DEX_SURSKIT			310
#define NATIONAL_DEX_MASQUERAIN		311
#define NATIONAL_DEX_SHROOMISH		312
#define NATIONAL_DEX_BRELOOM			313
#define NATIONAL_DEX_SLAKOTH			314
#define NATIONAL_DEX_VIGOROTH		315
#define NATIONAL_DEX_SLAKING			316
#define NATIONAL_DEX_NINCADA			317
#define NATIONAL_DEX_NINJASK			318
#define NATIONAL_DEX_SHEDINJA		319
#define NATIONAL_DEX_WHISMUR			320
#define NATIONAL_DEX_LOUDRED			321
#define NATIONAL_DEX_EXPLOUD			322
#define NATIONAL_DEX_MAKUHITA		323
#define NATIONAL_DEX_HARIYAMA		324
#define NATIONAL_DEX_NOSEPASS		325
#define NATIONAL_DEX_PROBOPASS		326
#define NATIONAL_DEX_SKITTY			327
#define NATIONAL_DEX_DELCATTY		328
#define NATIONAL_DEX_SABLEYE			329
#define NATIONAL_DEX_MAWILE			330
#define NATIONAL_DEX_ARON			331
#define NATIONAL_DEX_LAIRON			332
#define NATIONAL_DEX_AGGRON			333
#define NATIONAL_DEX_MEDITITE		334
#define NATIONAL_DEX_MEDICHAM		335
#define NATIONAL_DEX_ELECTRIKE		336
#define NATIONAL_DEX_MANECTRIC		337
#define NATIONAL_DEX_PLUSLE			338
#define NATIONAL_DEX_MINUN			339
#define NATIONAL_DEX_VOLBEAT			340
#define NATIONAL_DEX_ILLUMISE		341
#define NATIONAL_DEX_BUDEW			342
#define NATIONAL_DEX_ROSELIA			343
#define NATIONAL_DEX_ROSERADE		344
#define NATIONAL_DEX_GULPIN			345
#define NATIONAL_DEX_SWALOT			346
#define NATIONAL_DEX_CARVANHA		347
#define NATIONAL_DEX_SHARPEDO		348
#define NATIONAL_DEX_WAILMER			349
#define NATIONAL_DEX_WAILORD			350
#define NATIONAL_DEX_NUMEL			351
#define NATIONAL_DEX_CAMERUPT		352
#define NATIONAL_DEX_TORKOAL			353
#define NATIONAL_DEX_SPOINK			354
#define NATIONAL_DEX_GRUMPIG			355
#define NATIONAL_DEX_SPINDA			356
#define NATIONAL_DEX_TRAPINCH		357
#define NATIONAL_DEX_VIBRAVA			358
#define NATIONAL_DEX_FLYGON			359
#define NATIONAL_DEX_CACNEA			360
#define NATIONAL_DEX_CACTURNE		361
#define NATIONAL_DEX_SWABLU			362
#define NATIONAL_DEX_ALTARIA			363
#define NATIONAL_DEX_ZANGOOSE		364
#define NATIONAL_DEX_SEVIPER			365
#define NATIONAL_DEX_LUNATONE		366
#define NATIONAL_DEX_SOLROCK			367
#define NATIONAL_DEX_BARBOACH		368
#define NATIONAL_DEX_WHISCASH		369
#define NATIONAL_DEX_CORPHISH		370
#define NATIONAL_DEX_CRAWDAUNT		371
#define NATIONAL_DEX_BALTOY			372
#define NATIONAL_DEX_CLAYDOL			373
#define NATIONAL_DEX_LILEEP			374
#define NATIONAL_DEX_CRADILY			375
#define NATIONAL_DEX_ANORITH			376
#define NATIONAL_DEX_ARMALDO			377
#define NATIONAL_DEX_FEEBAS			378
#define NATIONAL_DEX_MILOTIC			379
#define NATIONAL_DEX_CASTFORM		380
#define NATIONAL_DEX_KECLEON			381
#define NATIONAL_DEX_SHUPPET			382
#define NATIONAL_DEX_BANETTE			383
#define NATIONAL_DEX_DUSKULL			384
#define NATIONAL_DEX_DUSCLOPS		385
#define NATIONAL_DEX_DUSKNOIR		386
#define NATIONAL_DEX_TROPIUS			387
#define NATIONAL_DEX_CHINGLING		388
#define NATIONAL_DEX_CHIMECHO		389
#define NATIONAL_DEX_ABSOL			390
#define NATIONAL_DEX_SNORUNT			391
#define NATIONAL_DEX_GLALIE			392
#define NATIONAL_DEX_FROSLASS		393
#define NATIONAL_DEX_SPHEAL			394
#define NATIONAL_DEX_SEALEO			395
#define NATIONAL_DEX_WALREIN			396
#define NATIONAL_DEX_CLAMPERL		397
#define NATIONAL_DEX_HUNTAIL			398
#define NATIONAL_DEX_GOREBYSS		399
#define NATIONAL_DEX_RELICANTH		400
#define NATIONAL_DEX_LUVDISC			401
#define NATIONAL_DEX_ALOMOMOLA		402
#define NATIONAL_DEX_BAGON			403
#define NATIONAL_DEX_SHELGON			404
#define NATIONAL_DEX_SALAMENCE		405
#define NATIONAL_DEX_BELDUM			406
#define NATIONAL_DEX_METANG			407
#define NATIONAL_DEX_METAGROSS		408
#define NATIONAL_DEX_REGIROCK		409
#define NATIONAL_DEX_REGICE			410
#define NATIONAL_DEX_REGISTEEL		411
#define NATIONAL_DEX_LATIAS			412
#define NATIONAL_DEX_LATIOS			413
#define NATIONAL_DEX_KYOGRE			414
#define NATIONAL_DEX_GROUDON			415
#define NATIONAL_DEX_RAYQUAZA		416
#define NATIONAL_DEX_JIRACHI			417
#define NATIONAL_DEX_DEOXYS			418
#define NATIONAL_DEX_TURTWIG			419
#define NATIONAL_DEX_GROTLE			420
#define NATIONAL_DEX_TORTERRA		421
#define NATIONAL_DEX_CHIMCHAR		422
#define NATIONAL_DEX_MONFERNO		423
#define NATIONAL_DEX_INFERNAPE		424
#define NATIONAL_DEX_PIPLUP			425
#define NATIONAL_DEX_PRINPLUP		426
#define NATIONAL_DEX_EMPOLEON		427
#define NATIONAL_DEX_STARLY			428
#define NATIONAL_DEX_STARAVIA		429
#define NATIONAL_DEX_STARAPTOR		430
#define NATIONAL_DEX_BIDOOF			431
#define NATIONAL_DEX_BIBAREL			432
#define NATIONAL_DEX_KRICKETOT		433
#define NATIONAL_DEX_KRICKETUNE		434
#define NATIONAL_DEX_SHINX			435
#define NATIONAL_DEX_LUXIO			436
#define NATIONAL_DEX_LUXRAY			437
#define NATIONAL_DEX_CRANIDOS		438
#define NATIONAL_DEX_RAMPARDOS		439
#define NATIONAL_DEX_SHIELDON		440
#define NATIONAL_DEX_BASTIODON		441
#define NATIONAL_DEX_BURMY			442
#define NATIONAL_DEX_WORMADAM		443
#define NATIONAL_DEX_MOTHIM			444
#define NATIONAL_DEX_COMBEE			445
#define NATIONAL_DEX_VESPIQUEN		446
#define NATIONAL_DEX_PACHIRISU		447
#define NATIONAL_DEX_BUIZEL			448
#define NATIONAL_DEX_FLOATZEL		449
#define NATIONAL_DEX_CHERUBI			450
#define NATIONAL_DEX_CHERRIM			451
#define NATIONAL_DEX_SHELLOS			452
#define NATIONAL_DEX_GASTRODON		453
#define NATIONAL_DEX_DRIFLOON		454
#define NATIONAL_DEX_DRIFBLIM		455
#define NATIONAL_DEX_BUNEARY			456
#define NATIONAL_DEX_LOPUNNY			457
#define NATIONAL_DEX_GLAMEOW			458
#define NATIONAL_DEX_PURUGLY			459
#define NATIONAL_DEX_STUNKY			460
#define NATIONAL_DEX_SKUNTANK		461
#define NATIONAL_DEX_BRONZOR			462
#define NATIONAL_DEX_BRONZONG		463
#define NATIONAL_DEX_CHATOT			464
#define NATIONAL_DEX_SPIRITOMB		465
#define NATIONAL_DEX_GIBLE			466
#define NATIONAL_DEX_GABITE			467
#define NATIONAL_DEX_GARCHOMP		468
#define NATIONAL_DEX_RIOLU			469
#define NATIONAL_DEX_LUCARIO			470
#define NATIONAL_DEX_HIPPOPOTAS		471
#define NATIONAL_DEX_HIPPOWDON		472
#define NATIONAL_DEX_SKORUPI			473
#define NATIONAL_DEX_DRAPION			474
#define NATIONAL_DEX_CROAGUNK		475
#define NATIONAL_DEX_TOXICROAK		476
#define NATIONAL_DEX_CARNIVINE		477
#define NATIONAL_DEX_FINNEON			478
#define NATIONAL_DEX_LUMINEON		479
#define NATIONAL_DEX_SNOVER			480
#define NATIONAL_DEX_ABOMASNOW		481
#define NATIONAL_DEX_ROTOM			482
#define NATIONAL_DEX_UXIE			483
#define NATIONAL_DEX_MESPRIT			484
#define NATIONAL_DEX_AZELF			485
#define NATIONAL_DEX_DIALGA			486
#define NATIONAL_DEX_PALKIA			487
#define NATIONAL_DEX_HEATRAN			488
#define NATIONAL_DEX_REGIGIGAS		489
#define NATIONAL_DEX_GIRATINA		490
#define NATIONAL_DEX_CRESSELIA		491
#define NATIONAL_DEX_PHIONE			492
#define NATIONAL_DEX_MANAPHY			493
#define NATIONAL_DEX_DARKRAI			494
#define NATIONAL_DEX_SHAYMIN			495
#define NATIONAL_DEX_ARCEUS			496

#define NATIONAL_DEX_COUNT NATIONAL_DEX_ARCEUS
#define POKEMON_SLOTS_NUMBER (NATIONAL_DEX_COUNT + 1)

// Hoenn Dex(ORAS) Index Defines
#define HOENN_DEX_NONE			0
#define HOENN_DEX_BULBASAUR		1
#define HOENN_DEX_IVYSAUR			2
#define HOENN_DEX_VENUSAUR		3
#define HOENN_DEX_CHARMANDER		4
#define HOENN_DEX_CHARMELEON		5
#define HOENN_DEX_CHARIZARD		6
#define HOENN_DEX_SQUIRTLE		7
#define HOENN_DEX_WARTORTLE		8
#define HOENN_DEX_BLASTOISE		9
#define HOENN_DEX_CATERPIE		10
#define HOENN_DEX_METAPOD			11
#define HOENN_DEX_BUTTERFREE		12
#define HOENN_DEX_WEEDLE			13
#define HOENN_DEX_KAKUNA			14
#define HOENN_DEX_BEEDRILL		15
#define HOENN_DEX_PIDGEY			16
#define HOENN_DEX_PIDGEOTTO		17
#define HOENN_DEX_PIDGEOT			18
#define HOENN_DEX_RATTATA			19
#define HOENN_DEX_RATICATE		20
#define HOENN_DEX_SPEAROW			21
#define HOENN_DEX_FEAROW			22
#define HOENN_DEX_EKANS			23
#define HOENN_DEX_ARBOK			24
#define HOENN_DEX_PICHU			25
#define HOENN_DEX_PIKACHU			26
#define HOENN_DEX_RAICHU			27
#define HOENN_DEX_SANDSHREW		28
#define HOENN_DEX_SANDSLASH		29
#define HOENN_DEX_NIDORAN_F		30
#define HOENN_DEX_NIDORINA		31
#define HOENN_DEX_NIDOQUEEN		32
#define HOENN_DEX_NIDORAN_M		33
#define HOENN_DEX_NIDORINO		34
#define HOENN_DEX_NIDOKING		35
#define HOENN_DEX_CLEFFA			36
#define HOENN_DEX_CLEFAIRY		37
#define HOENN_DEX_CLEFABLE		38
#define HOENN_DEX_VULPIX			39
#define HOENN_DEX_NINETALES		40
#define HOENN_DEX_IGGLYBUFF		41
#define HOENN_DEX_JIGGLYPUFF		42
#define HOENN_DEX_WIGGLYTUFF		43
#define HOENN_DEX_ZUBAT			44
#define HOENN_DEX_GOLBAT			45
#define HOENN_DEX_CROBAT			46
#define HOENN_DEX_ODDISH			47
#define HOENN_DEX_GLOOM			48
#define HOENN_DEX_VILEPLUME		49
#define HOENN_DEX_BELLOSSOM		50
#define HOENN_DEX_PARAS			51
#define HOENN_DEX_PARASECT		52
#define HOENN_DEX_VENONAT			53
#define HOENN_DEX_VENOMOTH		54
#define HOENN_DEX_DIGLETT			55
#define HOENN_DEX_DUGTRIO			56
#define HOENN_DEX_MEOWTH			57
#define HOENN_DEX_PERSIAN			58
#define HOENN_DEX_PSYDUCK			59
#define HOENN_DEX_GOLDUCK			60
#define HOENN_DEX_MANKEY			61
#define HOENN_DEX_PRIMEAPE		62
#define HOENN_DEX_GROWLITHE		63
#define HOENN_DEX_ARCANINE		64
#define HOENN_DEX_POLIWAG			65
#define HOENN_DEX_POLIWHIRL		66
#define HOENN_DEX_POLIWRATH		67
#define HOENN_DEX_POLITOED		68
#define HOENN_DEX_ABRA			69
#define HOENN_DEX_KADABRA			70
#define HOENN_DEX_ALAKAZAM		71
#define HOENN_DEX_MACHOP			72
#define HOENN_DEX_MACHOKE			73
#define HOENN_DEX_MACHAMP			74
#define HOENN_DEX_BELLSPROUT		75
#define HOENN_DEX_WEEPINBELL		76
#define HOENN_DEX_VICTREEBEL		77
#define HOENN_DEX_TENTACOOL		78
#define HOENN_DEX_TENTACRUEL		79
#define HOENN_DEX_GEODUDE			80
#define HOENN_DEX_GRAVELER		81
#define HOENN_DEX_GOLEM			82
#define HOENN_DEX_PONYTA			83
#define HOENN_DEX_RAPIDASH		84
#define HOENN_DEX_SLOWPOKE		85
#define HOENN_DEX_SLOWBRO			86
#define HOENN_DEX_SLOWKING		87
#define HOENN_DEX_MAGNEMITE		88
#define HOENN_DEX_MAGNETON		89
#define HOENN_DEX_MAGNEZONE		90
#define HOENN_DEX_FARFETCHD		91
#define HOENN_DEX_SIRFETCHD		92
#define HOENN_DEX_DODUO			93
#define HOENN_DEX_DODRIO			94
#define HOENN_DEX_SEEL			95
#define HOENN_DEX_DEWGONG			96
#define HOENN_DEX_GRIMER			97
#define HOENN_DEX_MUK				98
#define HOENN_DEX_SHELLDER		99
#define HOENN_DEX_CLOYSTER		100
#define HOENN_DEX_GASTLY			101
#define HOENN_DEX_HAUNTER			102
#define HOENN_DEX_GENGAR			103
#define HOENN_DEX_ONIX			104
#define HOENN_DEX_STEELIX			105
#define HOENN_DEX_DROWZEE			106
#define HOENN_DEX_HYPNO			107
#define HOENN_DEX_KRABBY			108
#define HOENN_DEX_KINGLER			109
#define HOENN_DEX_VOLTORB			110
#define HOENN_DEX_ELECTRODE		111
#define HOENN_DEX_EXEGGCUTE		112
#define HOENN_DEX_EXEGGUTOR		113
#define HOENN_DEX_CUBONE			114
#define HOENN_DEX_MAROWAK			115
#define HOENN_DEX_TYROGUE			116
#define HOENN_DEX_HITMONLEE		117
#define HOENN_DEX_HITMONCHAN		118
#define HOENN_DEX_HITMONTOP		119
#define HOENN_DEX_LICKITUNG		120
#define HOENN_DEX_LICKILICKY		121
#define HOENN_DEX_KOFFING			122
#define HOENN_DEX_WEEZING			123
#define HOENN_DEX_RHYHORN			124
#define HOENN_DEX_RHYDON			125
#define HOENN_DEX_RHYPERIOR		126
#define HOENN_DEX_HAPPINY			127
#define HOENN_DEX_CHANSEY			128
#define HOENN_DEX_BLISSEY			129
#define HOENN_DEX_TANGELA			130
#define HOENN_DEX_TANGROWTH		131
#define HOENN_DEX_KANGASKHAN		132
#define HOENN_DEX_HORSEA			133
#define HOENN_DEX_SEADRA			134
#define HOENN_DEX_KINGDRA			135
#define HOENN_DEX_GOLDEEN			136
#define HOENN_DEX_SEAKING			137
#define HOENN_DEX_STARYU			138
#define HOENN_DEX_STARMIE			139
#define HOENN_DEX_MIME_JR			140
#define HOENN_DEX_MR_MIME			141
#define HOENN_DEX_SCYTHER			142
#define HOENN_DEX_SCIZOR			143
#define HOENN_DEX_SMOOCHUM		144
#define HOENN_DEX_JYNX			145
#define HOENN_DEX_ELEKID			146
#define HOENN_DEX_ELECTABUZZ		147
#define HOENN_DEX_ELECTIVIRE		148
#define HOENN_DEX_MAGBY			149
#define HOENN_DEX_MAGMAR			150
#define HOENN_DEX_MAGMORTAR		151
#define HOENN_DEX_PINSIR			152
#define HOENN_DEX_TAUROS			153
#define HOENN_DEX_MAGIKARP		154
#define HOENN_DEX_GYARADOS		155
#define HOENN_DEX_LAPRAS			156
#define HOENN_DEX_DITTO			157
#define HOENN_DEX_EEVEE			158
#define HOENN_DEX_VAPOREON		159
#define HOENN_DEX_JOLTEON			160
#define HOENN_DEX_FLAREON			161
#define HOENN_DEX_ESPEON			162
#define HOENN_DEX_UMBREON			163
#define HOENN_DEX_LEAFEON			164
#define HOENN_DEX_GLACEON			165
#define HOENN_DEX_SYLVEON			166
#define HOENN_DEX_PORYGON			167
#define HOENN_DEX_PORYGON2		168
#define HOENN_DEX_PORYGON_Z		169
#define HOENN_DEX_OMANYTE			170
#define HOENN_DEX_OMASTAR			171
#define HOENN_DEX_KABUTO			172
#define HOENN_DEX_KABUTOPS		173
#define HOENN_DEX_AERODACTYL		174
#define HOENN_DEX_MUNCHLAX		175
#define HOENN_DEX_SNORLAX			176
#define HOENN_DEX_ARTICUNO		177
#define HOENN_DEX_ZAPDOS			178
#define HOENN_DEX_MOLTRES			179
#define HOENN_DEX_DRATINI			180
#define HOENN_DEX_DRAGONAIR		181
#define HOENN_DEX_DRAGONITE		182
#define HOENN_DEX_MEWTWO			183
#define HOENN_DEX_MEW				184
#define HOENN_DEX_CHIKORITA		185
#define HOENN_DEX_BAYLEEF			186
#define HOENN_DEX_MEGANIUM		187
#define HOENN_DEX_CYNDAQUIL		188
#define HOENN_DEX_QUILAVA			189
#define HOENN_DEX_TYPHLOSION		190
#define HOENN_DEX_TOTODILE		191
#define HOENN_DEX_CROCONAW		192
#define HOENN_DEX_FERALIGATR		193
#define HOENN_DEX_SENTRET			194
#define HOENN_DEX_FURRET			195
#define HOENN_DEX_HOOTHOOT		196
#define HOENN_DEX_NOCTOWL			197
#define HOENN_DEX_LEDYBA			198
#define HOENN_DEX_LEDIAN			199
#define HOENN_DEX_SPINARAK		200
#define HOENN_DEX_ARIADOS			201
#define HOENN_DEX_CHINCHOU		202
#define HOENN_DEX_LANTURN			203
#define HOENN_DEX_TOGEPI			204
#define HOENN_DEX_TOGETIC			205
#define HOENN_DEX_TOGEKISS		206
#define HOENN_DEX_NATU			207
#define HOENN_DEX_XATU			208
#define HOENN_DEX_MAREEP			209
#define HOENN_DEX_FLAAFFY			210
#define HOENN_DEX_AMPHAROS		211
#define HOENN_DEX_AZURILL			212
#define HOENN_DEX_MARILL			213
#define HOENN_DEX_AZUMARILL		214
#define HOENN_DEX_BONSLY			215
#define HOENN_DEX_SUDOWOODO		216
#define HOENN_DEX_HOPPIP			217
#define HOENN_DEX_SKIPLOOM		218
#define HOENN_DEX_JUMPLUFF		219
#define HOENN_DEX_AIPOM			220
#define HOENN_DEX_AMBIPOM			221
#define HOENN_DEX_SUNKERN			222
#define HOENN_DEX_SUNFLORA		223
#define HOENN_DEX_YANMA			224
#define HOENN_DEX_YANMEGA			225
#define HOENN_DEX_WOOPER			226
#define HOENN_DEX_QUAGSIRE		227
#define HOENN_DEX_MURKROW			228
#define HOENN_DEX_HONCHKROW		229
#define HOENN_DEX_MISDREAVUS		230
#define HOENN_DEX_MISMAGIUS		231
#define HOENN_DEX_UNOWN			232
#define HOENN_DEX_WYNAUT			233
#define HOENN_DEX_WOBBUFFET		234
#define HOENN_DEX_GIRAFARIG		235
#define HOENN_DEX_PINECO			236
#define HOENN_DEX_FORRETRESS		237
#define HOENN_DEX_DUNSPARCE		238
#define HOENN_DEX_GLIGAR			239
#define HOENN_DEX_GLISCOR			240
#define HOENN_DEX_SNUBBULL		241
#define HOENN_DEX_GRANBULL		242
#define HOENN_DEX_QWILFISH		243
#define HOENN_DEX_SHUCKLE			244
#define HOENN_DEX_HERACROSS		245
#define HOENN_DEX_SNEASEL			246
#define HOENN_DEX_WEAVILE			247
#define HOENN_DEX_TEDDIURSA		248
#define HOENN_DEX_URSARING		249
#define HOENN_DEX_SLUGMA			250
#define HOENN_DEX_MAGCARGO		251
#define HOENN_DEX_SWINUB			252
#define HOENN_DEX_PILOSWINE		253
#define HOENN_DEX_MAMOSWINE		254
#define HOENN_DEX_CORSOLA			255
#define HOENN_DEX_REMORAID		256
#define HOENN_DEX_OCTILLERY		257
#define HOENN_DEX_DELIBIRD		258
#define HOENN_DEX_MANTYKE			259
#define HOENN_DEX_MANTINE			260
#define HOENN_DEX_SKARMORY		261
#define HOENN_DEX_HOUNDOUR		262
#define HOENN_DEX_HOUNDOOM		263
#define HOENN_DEX_PHANPY			264
#define HOENN_DEX_DONPHAN			265
#define HOENN_DEX_STANTLER		266
#define HOENN_DEX_SMEARGLE		267
#define HOENN_DEX_MILTANK			268
#define HOENN_DEX_RAIKOU			269
#define HOENN_DEX_ENTEI			270
#define HOENN_DEX_SUICUNE			271
#define HOENN_DEX_LARVITAR		272
#define HOENN_DEX_PUPITAR			273
#define HOENN_DEX_TYRANITAR		274
#define HOENN_DEX_LUGIA			275
#define HOENN_DEX_HO_OH			276
#define HOENN_DEX_CELEBI			277
#define HOENN_DEX_TREECKO			278
#define HOENN_DEX_GROVYLE			279
#define HOENN_DEX_SCEPTILE		280
#define HOENN_DEX_TORCHIC			281
#define HOENN_DEX_COMBUSKEN		282
#define HOENN_DEX_BLAZIKEN		283
#define HOENN_DEX_MUDKIP			284
#define HOENN_DEX_MARSHTOMP		285
#define HOENN_DEX_SWAMPERT		286
#define HOENN_DEX_POOCHYENA		287
#define HOENN_DEX_MIGHTYENA		288
#define HOENN_DEX_ZIGZAGOON		289
#define HOENN_DEX_LINOONE			290
#define HOENN_DEX_WURMPLE			291
#define HOENN_DEX_SILCOON			292
#define HOENN_DEX_BEAUTIFLY		293
#define HOENN_DEX_CASCOON			294
#define HOENN_DEX_DUSTOX			295
#define HOENN_DEX_LOTAD			296
#define HOENN_DEX_LOMBRE			297
#define HOENN_DEX_LUDICOLO		298
#define HOENN_DEX_SEEDOT			299
#define HOENN_DEX_NUZLEAF			300
#define HOENN_DEX_SHIFTRY			301
#define HOENN_DEX_TAILLOW			302
#define HOENN_DEX_SWELLOW			303
#define HOENN_DEX_WINGULL			304
#define HOENN_DEX_PELIPPER		305
#define HOENN_DEX_RALTS			306
#define HOENN_DEX_KIRLIA			307
#define HOENN_DEX_GARDEVOIR		308
#define HOENN_DEX_GALLADE			309
#define HOENN_DEX_SURSKIT			310
#define HOENN_DEX_MASQUERAIN		311
#define HOENN_DEX_SHROOMISH		312
#define HOENN_DEX_BRELOOM			313
#define HOENN_DEX_SLAKOTH			314
#define HOENN_DEX_VIGOROTH		315
#define HOENN_DEX_SLAKING			316
#define HOENN_DEX_NINCADA			317
#define HOENN_DEX_NINJASK			318
#define HOENN_DEX_SHEDINJA		319
#define HOENN_DEX_WHISMUR			320
#define HOENN_DEX_LOUDRED			321
#define HOENN_DEX_EXPLOUD			322
#define HOENN_DEX_MAKUHITA		323
#define HOENN_DEX_HARIYAMA		324
#define HOENN_DEX_NOSEPASS		325
#define HOENN_DEX_PROBOPASS		326
#define HOENN_DEX_SKITTY			327
#define HOENN_DEX_DELCATTY		328
#define HOENN_DEX_SABLEYE			329
#define HOENN_DEX_MAWILE			330
#define HOENN_DEX_ARON			331
#define HOENN_DEX_LAIRON			332
#define HOENN_DEX_AGGRON			333
#define HOENN_DEX_MEDITITE		334
#define HOENN_DEX_MEDICHAM		335
#define HOENN_DEX_ELECTRIKE		336
#define HOENN_DEX_MANECTRIC		337
#define HOENN_DEX_PLUSLE			338
#define HOENN_DEX_MINUN			339
#define HOENN_DEX_VOLBEAT			340
#define HOENN_DEX_ILLUMISE		341
#define HOENN_DEX_BUDEW			342
#define HOENN_DEX_ROSELIA			343
#define HOENN_DEX_ROSERADE		344
#define HOENN_DEX_GULPIN			345
#define HOENN_DEX_SWALOT			346
#define HOENN_DEX_CARVANHA		347
#define HOENN_DEX_SHARPEDO		348
#define HOENN_DEX_WAILMER			349
#define HOENN_DEX_WAILORD			350
#define HOENN_DEX_NUMEL			351
#define HOENN_DEX_CAMERUPT		352
#define HOENN_DEX_TORKOAL			353
#define HOENN_DEX_SPOINK			354
#define HOENN_DEX_GRUMPIG			355
#define HOENN_DEX_SPINDA			356
#define HOENN_DEX_TRAPINCH		357
#define HOENN_DEX_VIBRAVA			358
#define HOENN_DEX_FLYGON			359
#define HOENN_DEX_CACNEA			360
#define HOENN_DEX_CACTURNE		361
#define HOENN_DEX_SWABLU			362
#define HOENN_DEX_ALTARIA			363
#define HOENN_DEX_ZANGOOSE		364
#define HOENN_DEX_SEVIPER			365
#define HOENN_DEX_LUNATONE		366
#define HOENN_DEX_SOLROCK			367
#define HOENN_DEX_BARBOACH		368
#define HOENN_DEX_WHISCASH		369
#define HOENN_DEX_CORPHISH		370
#define HOENN_DEX_CRAWDAUNT		371
#define HOENN_DEX_BALTOY			372
#define HOENN_DEX_CLAYDOL			373
#define HOENN_DEX_LILEEP			374
#define HOENN_DEX_CRADILY			375
#define HOENN_DEX_ANORITH			376
#define HOENN_DEX_ARMALDO			377
#define HOENN_DEX_FEEBAS			378
#define HOENN_DEX_MILOTIC			379
#define HOENN_DEX_CASTFORM		380
#define HOENN_DEX_KECLEON			381
#define HOENN_DEX_SHUPPET			382
#define HOENN_DEX_BANETTE			383
#define HOENN_DEX_DUSKULL			384
#define HOENN_DEX_DUSCLOPS		385
#define HOENN_DEX_DUSKNOIR		386
#define HOENN_DEX_TROPIUS			387
#define HOENN_DEX_CHINGLING		388
#define HOENN_DEX_CHIMECHO		389
#define HOENN_DEX_ABSOL			390
#define HOENN_DEX_SNORUNT			391
#define HOENN_DEX_GLALIE			392
#define HOENN_DEX_FROSLASS		393
#define HOENN_DEX_SPHEAL			394
#define HOENN_DEX_SEALEO			395
#define HOENN_DEX_WALREIN			396
#define HOENN_DEX_CLAMPERL		397
#define HOENN_DEX_HUNTAIL			398
#define HOENN_DEX_GOREBYSS		399
#define HOENN_DEX_RELICANTH		400
#define HOENN_DEX_LUVDISC			401
#define HOENN_DEX_ALOMOMOLA		402
#define HOENN_DEX_BAGON			403
#define HOENN_DEX_SHELGON			404
#define HOENN_DEX_SALAMENCE		405
#define HOENN_DEX_BELDUM			406
#define HOENN_DEX_METANG			407
#define HOENN_DEX_METAGROSS		408
#define HOENN_DEX_REGIROCK		409
#define HOENN_DEX_REGICE			410
#define HOENN_DEX_REGISTEEL		411
#define HOENN_DEX_LATIAS			412
#define HOENN_DEX_LATIOS			413
#define HOENN_DEX_KYOGRE			414
#define HOENN_DEX_GROUDON			415
#define HOENN_DEX_RAYQUAZA		416
#define HOENN_DEX_JIRACHI			417
#define HOENN_DEX_DEOXYS			418
#define HOENN_DEX_TURTWIG			419
#define HOENN_DEX_GROTLE			420
#define HOENN_DEX_TORTERRA		421
#define HOENN_DEX_CHIMCHAR		422
#define HOENN_DEX_MONFERNO		423
#define HOENN_DEX_INFERNAPE		424
#define HOENN_DEX_PIPLUP			425
#define HOENN_DEX_PRINPLUP		426
#define HOENN_DEX_EMPOLEON		427
#define HOENN_DEX_STARLY			428
#define HOENN_DEX_STARAVIA		429
#define HOENN_DEX_STARAPTOR		430
#define HOENN_DEX_BIDOOF			431
#define HOENN_DEX_BIBAREL			432
#define HOENN_DEX_KRICKETOT		433
#define HOENN_DEX_KRICKETUNE		434
#define HOENN_DEX_SHINX			435
#define HOENN_DEX_LUXIO			436
#define HOENN_DEX_LUXRAY			437
#define HOENN_DEX_CRANIDOS		438
#define HOENN_DEX_RAMPARDOS		439
#define HOENN_DEX_SHIELDON		440
#define HOENN_DEX_BASTIODON		441
#define HOENN_DEX_BURMY			442
#define HOENN_DEX_WORMADAM		443
#define HOENN_DEX_MOTHIM			444
#define HOENN_DEX_COMBEE			445
#define HOENN_DEX_VESPIQUEN		446
#define HOENN_DEX_PACHIRISU		447
#define HOENN_DEX_BUIZEL			448
#define HOENN_DEX_FLOATZEL		449
#define HOENN_DEX_CHERUBI			450
#define HOENN_DEX_CHERRIM			451
#define HOENN_DEX_SHELLOS			452
#define HOENN_DEX_GASTRODON		453
#define HOENN_DEX_DRIFLOON		454
#define HOENN_DEX_DRIFBLIM		455
#define HOENN_DEX_BUNEARY			456
#define HOENN_DEX_LOPUNNY			457
#define HOENN_DEX_GLAMEOW			458
#define HOENN_DEX_PURUGLY			459
#define HOENN_DEX_STUNKY			460
#define HOENN_DEX_SKUNTANK		461
#define HOENN_DEX_BRONZOR			462
#define HOENN_DEX_BRONZONG		463
#define HOENN_DEX_CHATOT			464
#define HOENN_DEX_SPIRITOMB		465
#define HOENN_DEX_GIBLE			466
#define HOENN_DEX_GABITE			467
#define HOENN_DEX_GARCHOMP		468
#define HOENN_DEX_RIOLU			469
#define HOENN_DEX_LUCARIO			470
#define HOENN_DEX_HIPPOPOTAS		471
#define HOENN_DEX_HIPPOWDON		472
#define HOENN_DEX_SKORUPI			473
#define HOENN_DEX_DRAPION			474
#define HOENN_DEX_CROAGUNK		475
#define HOENN_DEX_TOXICROAK		476
#define HOENN_DEX_CARNIVINE		477
#define HOENN_DEX_FINNEON			478
#define HOENN_DEX_LUMINEON		479
#define HOENN_DEX_SNOVER			480
#define HOENN_DEX_ABOMASNOW		481
#define HOENN_DEX_ROTOM			482
#define HOENN_DEX_UXIE			483
#define HOENN_DEX_MESPRIT			484
#define HOENN_DEX_AZELF			485
#define HOENN_DEX_DIALGA			486
#define HOENN_DEX_PALKIA			487
#define HOENN_DEX_HEATRAN			488
#define HOENN_DEX_REGIGIGAS		489
#define HOENN_DEX_GIRATINA		490
#define HOENN_DEX_CRESSELIA		491
#define HOENN_DEX_PHIONE			492
#define HOENN_DEX_MANAPHY			493
#define HOENN_DEX_DARKRAI			494
#define HOENN_DEX_SHAYMIN			495
#define HOENN_DEX_ARCEUS			496

// species flags
#define F_ULTRA_BEAST   (1 << 0)
#define F_ALOLAN_FORM   (1 << 1)
#define F_GALARIAN_FORM (1 << 2)

#endif  // GUARD_CONSTANTS_SPECIES_H
